# Generated by Django 5.1.2 on 2024-11-04 13:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('B_ID', models.AutoField(primary_key=True, serialize=False)),
                ('B_Name', models.CharField(max_length=50)),
                ('Grade', models.CharField(max_length=1)),
                ('B_Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Website', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('Branch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Br_Name', models.CharField(max_length=50)),
                ('Br_Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Br_Phone', models.CharField(max_length=10)),
                ('Bank_ID', models.ForeignKey(db_column='Bank_ID', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='banking.bank')),
            ],
            options={
                'db_table': 'Branch',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('C_id', models.AutoField(primary_key=True, serialize=False)),
                ('C_Name', models.CharField(max_length=50)),
                ('C_Address', models.CharField(blank=True, max_length=255, null=True)),
                ('DOB', models.DateField()),
                ('C_phone', models.CharField(max_length=10)),
                ('Nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Branch', models.ForeignKey(db_column='Branch_id', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='banking.branch')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Acc_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Acc_type', models.CharField(max_length=20)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Acc_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('Opened_date', models.DateField()),
                ('C_id', models.ForeignKey(db_column='C_id', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='banking.customer')),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('E_id', models.AutoField(primary_key=True, serialize=False)),
                ('E_Name', models.CharField(max_length=50)),
                ('Position', models.CharField(blank=True, max_length=50, null=True)),
                ('Salary', models.CharField(max_length=7)),
                ('Gender', models.CharField(blank=True, max_length=1, null=True)),
                ('E_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('Branch_id', models.ForeignKey(db_column='Branch_id', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='banking.branch')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('L_id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('Interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('Type', models.CharField(blank=True, max_length=15, null=True)),
                ('C_id', models.ForeignKey(db_column='C_id', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='banking.customer')),
            ],
            options={
                'db_table': 'Loan',
            },
        ),
        migrations.CreateModel(
            name='LoanStatusLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(blank=True, max_length=25, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Start_date', models.DateField(blank=True, null=True)),
                ('End_date', models.DateField(default='9999-12-31')),
                ('Tot_Amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('Cleared_Amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('Updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('Loan_purpose', models.TextField(blank=True, null=True)),
                ('C_id', models.ForeignKey(db_column='C_id', on_delete=django.db.models.deletion.CASCADE, related_name='loan_status_logs', to='banking.customer')),
                ('L_id', models.ForeignKey(db_column='L_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='banking.loan')),
            ],
            options={
                'db_table': 'LoanStatusLog',
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('N_id', models.AutoField(primary_key=True, serialize=False)),
                ('N_Name', models.CharField(max_length=50)),
                ('Relationship', models.CharField(max_length=50)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('C_id', models.ForeignKey(db_column='C_id', on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='banking.customer')),
            ],
            options={
                'db_table': 'Nominee',
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('T_id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
                ('T_type', models.CharField(max_length=50)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('INPROCESS', 'In Process'), ('DISCARDED', 'Discarded')], default='INPROCESS', max_length=10)),
                ('Acc_id', models.ForeignKey(db_column='Acc_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.account')),
            ],
            options={
                'db_table': 'TransactionLog',
            },
        ),
    ]
